### ISSUE TITLE
Projenin tam adı ne olacak?

### ISSUE THREAD

**Issue by harunsengul** [SelmanKahya/slayt#1]
Projenin tam adını öğrenebilir miyim? Grafiker değilim logo yapacağım, fakat elimden geldiğince güzel bir şey yapabileceğimi düşünüyorum.

**Comment by harunsengul** [comment]
Yeni pr açarak gönderebilirim abi.

**Comment by SelmanKahya** [comment]
@harunsengul simdilik Slayt olarak dusunuyorum, logo tasarlamak istedigin takdirde yeni bir issue acip gonderebilirsen sevinirim.
