### ISSUE TITLE
Bu projemde çalışacak takım arkadaşı arıyorum! (1500TL+)

### ISSUE THREAD

**Issue by SelmanKahya** [SelmanKahya/slayt#4]
Merhaba!

## Mentörlük Konsepti
Topluluk üyeleri arasından bu projede benimle çalışmak isteyen bir takım arkadaşı arıyorum. **[Topluluk.org](www.topluluk.org)** üzerinden oluşumla alakalı detaylara ulaşabilirsiniz. Mentorlük programı altında proje geliştirmekte neleri hedeflediğimi hızlıca aktardıktan sonra bu proje ile alakalı detaylara geçeceğim.

Bu proje Topluluk organizasyonunun **MENTÖRLÜK** konusundaki ilk somut deneyimi olacak. Bu projenin geliştirilmesinden öğrendiklerimizle benzer modeli daha büyük projelere başarıyla uygulayabileceğimizi düşünüyorum.

### Aktörler
- Proje yöneticisi (Selman K)
- Takım üyesi (sen! 😍)

### Roller
**Proje yöneticisi:** Projenin başarıyla yayına alınması için gerekli tüm şartları sağlamakla yükümlü kişi olacak. Genellikle kişi ve kaynak yönetimi ($) konusunda kararları verecek.

[Scrum](https://tr.wikipedia.org/wiki/Scrum) yöntemiyle geliştirilecek projelerde yapılacak işleri küçük parçalara (epic/milestone) bölünmesinden sorumlu olduğu gibi takım üyelerinin bu parçaları daha da küçük, sindirilebilir parçalara ayırarak her sprintte adım adım bitirilmesini takip etmekten de sorumlu olacak.

**Takım üyesi:** Proje yöneticisi tarafından kabaca tarif edilen story'leri (hikaye) küçük feature'lere (özellik) böldükten sonra kendisi için proje tahtasında task'ler oluşturup her sprint kendi işini planlamaktan sorumludur.

Sprint başlangıcında o zaman diliminde üzerinde çalışacağı task'lerin herbiri için yapılacak işi kaliteli bir formatta dökümante edip, bir zaman tahmininde bulunup o görevi bitirmeye çalışıyor olacak.

### Senin Çıkarın Nedir?
Projede çalışacak kişi için hedeflenen birincil çıkarım edineceği tecrübe. Beş-on dakikalık bir konuşma, ya da soru cevapla aktarılmaya çalışılan tecrübeden ziyade tecrübeli bir kişiyle uzun soluklu bir projede yer almak arasında çok büyük bir fark var. 

Bu projede benimle çalışmak isteyen kişiye vadettiğim ilk şey Minted, Yahoo, Uber gibi şirketlerde edindiğim 6-7+ senelik profesyonel tecrübeyi yoğun bir şekilde sana aktaracak olmam. Kişisel deneyimlerimden yola çıkarak verdiğim kararları detaylıca konuşabilieceğimiz, teknik meselelerde bilgi alış-verişinde bulunabileceğimiz interaksiyonları bolca yaşacayağız. Kodları sürekli yakından inceliyor ve geribildirimde bulunuyor olacağım, terlemeye hazır ol :)

İkinci husus ise bu zamanını benim projeme ayırdığın için maddi olarak bir destekte bulunacak olmam. Projeden projeye ve sürece bağlı olarak bu rakam değişiyor olacak.

### Benim Çıkarım Nedir?
Vakit bulamayıp hayata geçiremediğim fikirleri efektif bir şekilde pazara sunup geribildirim almak ve fikirlerimi hızlıca validate etmek. Kariyerimde bu noktaya gelene kadar defalarca yaptığım şeyleri her projede tekrarlamak ve belli bir noktaya getirmek için gereken zamanı atlayıp, olayın orta noktasına hızlıca geçebilmek istiyorum.

Topluluk, Youtube, LinkedIn ve farklı platformlarda elimden geldiğince uygulamaya çalıştığım tecrübe aktarımını teknik manada da derin bir şekilde devam ettirmem için bu yolun ideal olduğunu düşünüyorum.

## Proje Detayları: Slayt
Konsept ilgini çektiyse okumaya devam et!

Birkaç ay önce canlı yayında geliştirmeye başladığım Slayt adında bir web uygulaması var. Bu fikrin ilerleyip güzel bir iş modeline dönüşebileceğine inanıyorum. Gündelik uğraşlardan projeyi devam ettirebilme fırsatım olmadı.

4 Youtube canlı yayında ilerlettiğim bu projenin son video kaydı burada:
[TIKLA](https://www.youtube.com/watch?v=t2SUJGERoZ4&index=1&list=PLTXQHe5cDvq18znAaIdt7vSqXGTQ9kn_i
)

Koda buradan ulaşabilirsiniz:
https://github.com/ToplulukTR/slayt

Kısaca; kişiler video-müzik-görselleri arka arkaya sıralayıp sonra sunum şeklinde sırayla hepsini ekrana yalın bir şekilde yansıtıp, bir etklinlik ortamındaki katılımcılara daha keyifli vakit geçirtebilecekler.

Bu fikri kısmen farklı bir alana pivot ettirmek istiyorum, beraber çalışmak üzere anlaştığımız takdirde ilerletmek istediğim yönü daha detaylı konuşacağız.

### Kullanılan teknolojiler
- HTML, CSS
- Javascript (react, redux)
- [Razzle](https://github.com/jaredpalmer/razzle)
- [Grommet](https://grommet.io/)
- Nodejs

Beraber çalışabilmemiz için bu teknolojilere aşina olmanı ve sergileyebileceğin projeler olmasını bekliyorum.

### Kod geliştirme süreci
Projeyi geliştirmek için şu tahtayı kullanacağız:
https://github.com/ToplulukTR/slayt/projects/1

Üzerinde çalıştığın her görevi dökümante etmeni ve tahtayı güncel tutmanı bekliyor olacağım. Gönderdiğin Pull Request'leri yakından inceleyip code review konusunda seni biraz terleteceğim.

Tüm bu süreç Topluluk üyeleri tarafından takip edilebiliyor olacak, fakat proje yöneticilerinin dışında müdahale söz konusu olmayacak. 

Seninle birkaç saatlik beyin fırtınası sonrası önümüzdeki 3-4 haftalık (1-2 sprint) işi belirleyip hareket etmek uygun görünüyor.

### Ödenek
Bunu birebirde detaylıca konuşup ortak bir rakamda buluşabileceğimize inanıyorum. Saatlik ya da milestone usulü ilerlemeye açığım.

# Benimle çalışmak istiyor musun?
Bu konsept ilgini çekti ve bu proje üzerinde benimle çalışmak istiyorsan aşağıya (bu issue üzerine) şu şekilde bir yorum bırakabilirsin:

```
İlgileniyorum!
Email: email@adresin.com
LinkedIn: https://www.linkedin.com/in/...
Ozgecmis linki: ...
Portfolyo: (yayında ya da koduna bakabileceğim uygulamaların listesi)
```

Cevabını bekliyorum! Görüşmek üzere,
Selman

**Comment by mrlkn** [comment]
İlgileniyorum!
Email: omeralkin7@gmail.com
LinkedIn: www.linkedin.com/in/omeralkin
Ozgecmis linki: www.omeralkin.com
Portfolyo : şuanlık yok maalesef
Not : Aradığınız tecrübedeki aday kesinlikle benim diyemem fakat “sizinle kendimi geliştirme” fırsatı için şansımı denemek istedim.

**Comment by batuhanakin** [comment]
İlgileniyorum!
Email: batuhanhasanakin@gmail.com
LinkedIn: https://www.linkedin.com/in/batuhan-hasan-akin-631190130/
Ozgecmis linki: https://drive.google.com/file/d/1TZYYSZVkI1nt9cryaj0lH3r5TKLz5JnX/view?usp=sharing
Portfolyo: -
Not: Ericsson stajim sirasinda kendi gelisimim icin firebase kullanarak stok islemlerinin saglanacagi bir uygulama ile ugrasmistim.

**Comment by Dentrax** [comment]
İlgileniyorum!
Email: furkan.turkal@hotmail.com
LinkedIn: https://www.linkedin.com/in/furkanturkal
Portfolyo: 
https://play.google.com/store/apps/developer?id=Furkan+T%C3%BCrkal (Projelerde Firebase kullanıldı)
https://github.com/Dentrax (Open Source Projects)
Not: JS konusunda giriş seviye sayılırım. Front-End konusu çok ilgimi çekmiyor Back-End'e göre. Firebase'i yaklaşık 2 yıl aktif olarak kullandım. Kendimi Project Management konusunda geliştireceğini düşünüyorum. Şansımı deneyebilirim. :)
Edit: Ücret beklentim yok, hedefim collaboration konusunda tecrübe kazanmak.

**Comment by MustafaOnurKilinc** [comment]
İlgileniyorum!
Mail: onurk@artsistem.com
Linkedin: https://www.linkedin.com/in/mustafa-onur-kilinç-74708231?originalSubdomain=tr
Portfolyo: Şu an hazırda paylaşabileceğim bir link yok ve bu post u hemen yanıtlamak istedim. Ama kodu incelemen için sayısız front-end, back-end uygulaması mevcut. Html, Css, javascript, node, vue vuex, .net.....

**Comment by bilalkaya** [comment]
İlgileniyorum!
Mail:bbilalkaya@gmail.com
Linkedin: https://www.linkedin.com/in/bilal-kaya-97424b133/
Portfolyo: Html, css ve native javascript üzerine bilgim mevcut. Javascript framework hiç kullanmadım. Bu konularda kendimi geliştirmeye çok hevesli olmam ve öğrenmeye bolca vaktim olduğu için işi yapabileceğimi düşünüyorum.

**Comment by bilakon** [comment]
İlgileniyorum!
Email: bilakon@gmail.com
LinkedIn: https://www.linkedin.com/in/bilalkisa
Ozgecmis linki: www.bilakon.com
Portfolyo: https://github.com/bilakon / Şuan üzerinde çalıştığım android projesini bitbucket repo'da saklıyorum, onu da isteğe göre açabilirim. ( Bu sene staj yaptığım yerde başladığım bir deneme projesi niteliğinde )

**Comment by omerfarukcifci** [comment]
İlgileniyorum!
Email: farukomer535@gmail.com
LinkedIn: https://www.linkedin.com/in/ömerfarukçifci
Ozgecmis linki: https://github.com/omerfarukcifci/samplerepository/blob/master/omerfarukcifci.pdf
Portfolyo: https://github.com/omerfarukcifci/
/* Şuan part time olarak çalıştığım ofiste web projelerinde react kullanıyorum */

**Comment by mhmtygt** [comment]
İlgileniyorum!
Mail:mahmutygt96@hotmail.com
Linkedin:https://www.linkedin.com/in/mahmut-yigit/
Özgeçmiş:https://drive.google.com/open?id=1eBHwm2PspXaEpp6XbzSRvdZ1LzrTQtti
Portfolyo:Uçtan uca RSA-1024 algoritmasıyla şifreli realtime chat uygulaması geliştirdim(android).Backend kısmında node.js ile firebase functions yazdım.
Not:Daha önce böyle bir web projesi içerisinde yer almadım.Geçtiğimiz dönem mezun oldum.Acemi olduğumu belirtmek isterim.Daha çok, öğrenmek ve tecrübe kazanmak için başvuru yapıyorum.Teşekkürler.

**Comment by safakkizkin** [comment]
İlgileniyorum!
Email: safakkizkin@gmail.com
LinkedIn: https://www.linkedin.com/in/safakkizkin
Ozgecmis linki: https://safakkizkin.com/pdf/resume.pdf
Portfolyo: http://homeocure.net ve https://bitbucket.org/safakkizkin/

**Comment by mertgulec** [comment]
İlgileniyorum!
Email: mertgulecwm@gmail.com
LinkedIn: https://www.linkedin.com/in/mert-gulec/
Ozgecmis linki: https://www.linkedin.com/in/mert-gulec/
Portfolyo:  https://www.behance.net/mertgulecwcefb

Design, HTML/CSS/Bootstrap/ ve SEO konulari ile ilgili yardimci olabilirim. 
Not: Ucret beklentim yok. Projeye katiliminin vizyonumu gelistirecegini dusunuyorum.

**Comment by arifemrecelik** [comment]
İlgileniyorum!
Email: ce.arifemre@gmail.com
LinkedIn: https://www.linkedin.com/in/arifemrecelik
Ozgecmis linki: https://drive.google.com/open?id=1ZI9RLt0ddk9nvt-1YxNyIVGwfgO563zJ
Portfolyo: Genelde geliştirdiğim projeleri hep firmalara geliştirdiğim için malesef kodlarını paylaşamıyorum. Fakat şu anda Allianz ve Turkcell bünyesinde içinde bulunduğum yayında olan projeler mevcuttur.

Not: Şu an iş değiştirme arefesindeyim yeni şirketimde React ile sıfırdan bir projeye başlıyoruz. Onun dışında 1 yılı aşkın front end developer geçmişim var.

**Comment by omeryaldirgan** [comment]
İlgileniyorum!
Email: omeryaldirgan@hotmail.com
LinkedIn: https://www.linkedin.com/in/omeryaldirgan/
Ozgecmis linki:https://omeryaldirgan.com/ 
Portfolyo: https://omeryaldirgan.com/cv.pdf 
Ek Github: https://github.com/gomulusistemlerdersi

**Comment by myusufkaya** [comment]
İlgileniyorum!
Email: yusufkayabm@gmail.com
LinkedIn: https://www.linkedin.com/in/yusufkayabm/
Ozgecmis linki: https://drive.google.com/open?id=1SSHFEABeGG_q_qjrQFuFW8Ae4hQmS1xh
Portfolyo: www.myusufkaya.com (Projelerim-Github linkim sitemde yer almaktadır.)

**Comment by gokhanap** [comment]
İlgileniyorum!
Email: gapay84@gmail.com
LinkedIn: https://www.linkedin.com/in/gapaydin
Ozgecmis linki: Kişisel bilgi hassasiyeti nedeniyle burada paylaşmıyorum.
Portfolyo: https://www.gokhanapaydin.com

**Comment by semademir97** [comment]
İlgileniyorum!
Email: sema.demir.1997@gmail.com
LinkedIn: https://www.linkedin.com/in/sssemademir/
Ozgecmis linki: LinkedIn profilimde özgeçmişim eklidir.
Portfolyo: https://github.com/semademir97

**Comment by kadirselki** [comment]
İlgileniyorum!
Email: selkikadir@gmail.com 
LinkedIn: https://www.linkedin.com/in/kadir-selki-8a9400146
Ozgecmis linki: http://kadirselki.com/me.html
Portfolyo: http://kadirselki.com/me.html

**Comment by mksglu** [comment]
E-mail: info[at]mkoseoglu.com
Linkedin: https://www.linkedin.com/in/mksglu
O&P: https://github.com/mksglu

Sevgiler,
Mert.

**Comment by candelibas** [comment]
İlgileniyorum!
Email: candelibas00@gmail.com
LinkedIn: https://www.linkedin.com/in/can-deliba%C5%9F-a27b5079/
Portfolyo: https://github.com/candelibas

**Comment by mert574** [comment]
İlgileniyorum!

- Email: mert574{at}gmail.com
- LinkedIn: https://www.linkedin.com/in/mert-yildiz
- Ozgecmis linki: https://docs.google.com/document/d/11jc8Ud8IzjjShCAKHZrXB1JJnOmTvs4Qu4hJE4-6n48/edit?usp=sharing
- Portfolyo: https://github.com/mert574

**Comment by abkucuk** [comment]
İlgileniyorum!
Email: ahmetbkucuk@gmail.com
LinkedIn: https://www.linkedin.com/in/ahmet-burak-k%C3%BC%C3%A7%C3%BCk-437196106/
Ozgecmis linki: https://drive.google.com/open?id=1q6KrZiFs5PEh1IHORnx2Alw_UKdcblpD
Portfolyo: https://github.com/abkucuk

**Comment by bariscc** [comment]
İlgileniyorum!
Email: bcanceylan[at]gmail.com
LinkedIn: https://www.linkedin.com/in/bcanceylan
Ozgecmis linki: https://drive.google.com/open?id=1gyRREjLUopEvbEDK9oz06oe2hdljCNSA
Portfolyo: bariscc.me

**Comment by Kirteke** [comment]
İlgileniyorum!
Mail:kirteke.hacer@gmail.com
Linkedin: https://www.linkedin.com/in/hacer-kirteke-1611a4105/
Özgeçmiş: https://drive.google.com/drive/u/0/my-drive
Portfolyo: -
Not:Önceligim kendimi geliştirmek.

**Comment by SelmanKahya** [comment]
Arkadaslar, ilginiz icin tesekkurler. Yorum eklemeyi kapatiyorum.

Onumuzdeki gunlerde bir sonuca baglayip buraya giris ekleyen herkese mail ile cevap yazacagim. Gorusmek uzere.

**Comment by vcard-username** [comment]
İlgileniyorum!
Email: tolunay.emre.cavdar@gmail.com
LinkedIn: https://www.linkedin.com/in/tolunay-emre-çavdar
Ozgecmis linki: E-mail olarak gönderdim.
Portfolyo: Şuan aktif olmayan İstanbul için deprem projesi.

- Yazılımda neredeyse her alan dikkatimi çektiği için yaklaşık olarak 2017 yılından itibaren Full-Stack olarak kendimi geliştirmekteyim. Asıl ilgi alanım ve iyi olduğuma inandığım taraf 'back-end'. Bunun yanında sıkı bir JavaScript tutkunuyum. Güncel frameworkler üzerine(React & React Native, Vue.js, Node.js vb.) sürekli olarak kendimi geliştirmekteyim.
Teşekkürler..
